# Generated by Django 5.2 on 2025-05-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('course', models.CharField(max_length=40)),
                ('descripition', models.TextField()),
                ('type', models.CharField(max_length=40)),
            ],
        ),
    ]
