# Generated by Django 5.2 on 2025-05-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='type',
            new_name='Ingredients',
        ),
    ]
