# Generated by Django 5.2 on 2025-05-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_type_recipes_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='isfav',
            field=models.BooleanField(default=False),
        ),
    ]
