# Generated by Django 5.2 on 2025-05-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_recipes_isfav'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('isadmin', models.BooleanField(default=False)),
            ],
        ),
    ]
