# Generated by Django 5.2.1 on 2025-05-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Ingredients',
            field=models.CharField(max_length=100),
        ),
    ]
